post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "title": "Python juttuja",
  "author": "Lisa Mac",
  "url": "https://pythona.com/",
  "likes": 9,
  "user": "64ae6d4b351b077652db86a4"
}
